---
abstract: 'A wrapper for all of table_info(), column_info(), *_key_info()'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Admin-TableInfo
provides:
  DBIx::Admin::TableInfo:
    file: lib/DBIx/Admin/TableInfo.pm
    version: 2.07
requires:
  Carp: 0
  DBI: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 2.07
