---
abstract: 'A wrapper for all of table_info(), column_info(), *_key_info()'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '0'
  Test::Version: '1.002003'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Admin-TableInfo
provides:
  DBIx::Admin::TableInfo:
    file: lib/DBIx/Admin/TableInfo.pm
    version: '3.01'
requires:
  DBI: '0'
  Data::Dumper::Concise: '2.022'
  Lingua::EN::PluralToSingular: '0.14'
  Moo: '1.004002'
  Text::TabularDisplay: '1.38'
  strict: '0'
  warnings: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '3.01'
