---
name: DBIx-Admin-TableInfo
version: 2.00
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: 'A wrapper for table_info(), column_info(), *_key_info()'
license: artistic
requires:
  Carp: 0
  DBI: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  DBIx::Admin::TableInfo:
    file: lib/DBIx/Admin/TableInfo.pm
    version: 2.00
generated_by: Module::Build version 0.2611
